# Config file for Air (https://github.com/air-verse/air)

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
# Command to build the application
# We use the main.go file in the root directory
cmd = "go build -o ./tmp/extract-data-go ./main.go"
# Binary file yields from `cmd`.
bin = "tmp/extract-data-go"
# Watch these filename extensions.
include_ext = ["go"]
# Ignore these directories.
# Added 'bin' from our Makefile setup
exclude_dir = ["tmp", "bin", "vendor"]
# Exclude specific regular expressions.
exclude_regex = ["_test\\.go"]
# Log file location
log = "air_build.log"
# Stop running old binary when build errors occur.
stop_on_error = true

[log]
# Show log time
time = true

[color]
# Customize colors
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true

[screen]
clear_on_rebuild = true

# Proxy is disabled as this is likely an API
# [proxy]
# enabled = false
